# *NUMPY BASIC FUNCTIONS*

In [2]:
import numpy as np
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#One dimentional array
a = np.array([1,2,3])
a.ndim

1

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim

2

In [4]:
a.itemsize #Print the size of the each item in the array
#size is the integer is 4

4

In [2]:
a.dtype

dtype('int32')

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.float64)
a
a.dtype

dtype('float64')

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [8]:
a.itemsize

16

In [9]:
a.size #print the total size of the array

9

In [10]:
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [11]:
a.shape

(3, 3)

In [20]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
import numpy as np
l = range(5)
l
l[0]
l[3]
# similarly for numpy there is arange 
a = np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [12]:
# for arange function arange(start,endpoint, step)
a = np.arange(0,20,2) # step of 2 between 1 to 10
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# linspace is diferent from arange

a = np.linspace(1,2,5)
# it will generate 10 numbers between 1 to 5
# initialization np.linspace(start, stop , numberofelements)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
a = np.linspace(1,5,5)
a

array([1., 2., 3., 4., 5.])

In [18]:
a = np.linspace(1,5,20)
a

array([  1.        ,  27.26315789,  53.52631579,  79.78947368,
       106.05263158, 132.31578947, 158.57894737, 184.84210526,
       211.10526316, 237.36842105, 263.63157895, 289.89473684,
       316.15789474, 342.42105263, 368.68421053, 394.94736842,
       421.21052632, 447.47368421, 473.73684211, 500.        ])

In [19]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a.shape

(3, 2)

In [21]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
b = a.ravel() # to flaten the array
b

array([1, 2, 3, 4, 5, 6])

## *Agregate Fucntions*


In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a.min()

1

In [26]:
a.max()

6

In [27]:
a.sum()

21

In [28]:
a.sum(axis = 0)

array([ 9, 12])

In [29]:
a.sum(axis = 1)

array([ 3,  7, 11])

In [26]:
import numpy as np
np.sqrt(a) 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [31]:
np.std(a) # standard deviation

1.707825127659933

In [32]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [33]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [34]:
a + b

array([[ 6,  8],
       [10, 12]])

In [35]:
a - b

array([[-4, -4],
       [-4, -4]])

In [36]:
a * b

array([[ 5, 12],
       [21, 32]])

In [37]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [38]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [25]:
import numpy as np

a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
import numpy as np

print(np.__version__)

1.23.4


In [34]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [35]:
type(arr)

numpy.ndarray

## Numpy Array Slicing

In [37]:
arr = np.arange(1,10)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
print(arr[0:5])

[1 2 3 4 5]
