## NUMPY FUNCTION PRACTICE

Reshape Mehods

In [34]:
import numpy as np

x = np.array([[1,2,3,4,5],[6,7,8,9,11]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [14]:
x.shape

(2, 5)

In [35]:
c = x.flatten()
c[2] = 33
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [32]:
d = x.ravel()
d[2] = 44

array([[ 1,  2, 44,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [36]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [39]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [43]:
x.resize(5,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [44]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [49]:
x.resize(2,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [57]:
np.vsplit(x,2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 11]])]

In [67]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])

In [74]:
np.hstack((x1,x2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])